name: Helm Lint and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add stakewise https://charts.stakewise.io
          helm repo update

      - name: Install Helm dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Installing dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Lint Helm charts
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Linting $chart"
              helm lint "$chart"
            fi
          done

      - name: Template Helm charts
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Templating $chart"
              helm template test "$chart" --debug
            fi
          done

      - name: Package Helm charts
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart"
              helm package "$chart"
            fi
          done

      - name: Run Helm tests (if available)
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Checking for tests in $chart"
              if [ -d "$chart/templates/tests" ]; then
                echo "Test templates found in $chart"
                # Note: Actual test execution would require a Kubernetes cluster
                # This step validates that test templates can be rendered
                helm template test "$chart" --show-only templates/tests/ || true
              else
                echo "No test templates found in $chart - skipping"
              fi
            fi
          done